name: example 
description: "Gesture Recorder Example"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gesture_recorder:
    path: ../
  scribble: ^0.10.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
