name: gesture_recorder
description: "gesture_recorder enables you to record and replay gesture events"
version: 0.3.0
homepage: https://github.com/chooyan-eng/gesture_recorder
repository: https://github.com/chooyan-eng/gesture_recorder

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vm_service: ^15.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
